### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by dxcqcv** [eugeneware/replacestream#37]
node -v 
8.5.0

    "replacestream": "^4.0.3",

real code like
```
    fs.createReadStream(oldPath, 'utf8')
      .pipe(replaceStream(makeRegex ,replaceFn.bind(this, replaceObj), {maxMatchLen: 5000}))
      .pipe(writable)
```

regexp like
```
<p id="btnWords".*?data-linkwords=.*?>
```

stream file like
```
... 
            <li id="lotteryBtn" class="startBtn" relative @touchStart="startLottery"  data-event="">
              <img src="img/mian_button_normal.png" alt="" id="normalBtn" class="normal_btn" v-show="!isDown">
              <img src="img/mian_button_selected.png" alt="" id="selectedBtn" class="selected_btn" v-show="isDown">
              <p id="btnWords" class="btn_words" :class="{btn_words_down:isDown}" data-activityid="oo" data-freeactivityid="tt" data-integral="10" data-appsharecode="" data-link="http://www.bing.com" data-linkwords="share" ref="btnWords">10 integrals</p>
              <p class="bonus_words" :class='{bonus_words_down:isDown}'>integral
                <span id="totalIntegral">{{ totalIntegral | formatNum }}</span>
              </p>

            </li>
...
```

error code
```
D:\dev\gitlab\auto-activity\node_modules\replacestream\index.js:51
        rewritten += dataToAppend;
                     ^

RangeError: Invalid string length
    at Transform.transform [as _transform] (D:\dev\gitlab\auto-activity\node_modules\replacestream\index.js:51:22)
    at Transform._read (D:\dev\gitlab\auto-activity\node_modules\readable-stream\lib\_stream_transform.js:182:10)
    at Transform._write (D:\dev\gitlab\auto-activity\node_modules\readable-stream\lib\_stream_transform.js:170:83)
    at doWrite (D:\dev\gitlab\auto-activity\node_modules\readable-stream\lib\_stream_writable.js:406:64)
    at writeOrBuffer (D:\dev\gitlab\auto-activity\node_modules\readable-stream\lib\_stream_writable.js:395:5)
    at Transform.Writable.write (D:\dev\gitlab\auto-activity\node_modules\readable-stream\lib\_stream_writable.js:322:11)
    at ReadStream.ondata (_stream_readable.js:642:20)
    at emitOne (events.js:115:13)
    at ReadStream.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:249:13)
    at ReadStream.Readable.push (_stream_readable.js:211:10)
    at onread (fs.js:2059:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:665:17)

```

I found the match string is only 13 words 224 characters, it's not very long, why show this error?

**Comment by dxcqcv** [comment]
sorry, my code is wrong
